spring.application.name=kitsuneApi

spring.datasource.url=jdbc:postgresql://localhost:5433/animedb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

consumet.api.url=http://localhost:3000
properties.api=api/
properties.api.anime=api/anime

consumet.provider.primary=animekai
consumet.provider.fallback=animepahe

consumet.endpoint.search=/{provider}/{query}
consumet.endpoint.info=/{provider}/info/{id}
consumet.endpoint.watch=/{provider}/watch/{episodeId}