spring.application.name=kitsuneApi

spring.datasource.url=jdbc:postgresql://localhost:5433/animedb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

consumet.api.url=http://localhost:3000
frontend.api.url=http://localhost:5173

properties.api.anime=/api/anime
properties.api.user=/api/user
properties.api.media=/api/media

consumet.path.anilist=/meta/anilist
consumet.path.anime=/anime/animekai
consumet.path.manga=/meta/anilist-manga
